version: "3.8"

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: aegonish_blog
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: aegonish-blog:local
    depends_on:
      - mongo
    environment:
      DOCKER_ENV: "true"
      NODE_ENV: production
      PORT: 4000
      MONGO_URI: mongodb://mongo:27017/aegonish_blog   # ✅ explicitly override localhost
      GOOGLE_DRIVE_FOLDER_ID: ${GOOGLE_DRIVE_FOLDER_ID}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      GOOGLE_REFRESH_TOKEN: ${GOOGLE_REFRESH_TOKEN}
    ports:
      - "4000:4000"
    restart: on-failure

volumes:
  mongo-data:
