apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.name" . }}
  namespace: aegonish
spec:
  selector:
    app: {{ include "frontend.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
