# k8s/secrets.local.yaml (used manually for local)
apiVersion: v1
kind: Secret
metadata:                                                      
  name: google-oauth
  namespace: aegonish
type: Opaque
stringData:
  GOOGLE_DRIVE_FOLDER_ID: "1oxZH7gdKZ9zdFm_trrwrup0JyItZJa6F"
  GOOGLE_CLIENT_ID: "387697027327-efkrn46i5cca3dc6lcei0l35m91ddm0t.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  GOOGLE_REDIRECT_URI: "https://developers.google.com/oauthplayground"
  GOOGLE_REFRESH_TOKEN: "1//045MTy8j55X9mCgYIARAAGAQSNwF-L9IrJDjubJZ5D6rb1CZvIfsnPhLi5FXSyYDsTKp72raW3PWw3UQXbHtptR-PHKh82pca730"
  MONGO_URI: "mongodb://127.0.0.1:27017/aegonish_blog"
  PORT: "4000"