replicaCount: 1
image:
  repository: mongo
  tag: 6.0
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  storageClass: ""      # leave empty for default storage class
  accessMode: ReadWriteOnce
  size: 2Gi

service:
  port: 27017
